name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-24.04
    steps:
      - name: Run release-please
        uses: googleapis/release-please-action@ef9c2745dbfb629d38ebfafa3347a81ab2d51409
        with:
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json
          token: ${{ secrets.RELEASE_AUTOMATION_TOKEN }}
